#!/bin/bash
source $PWD/container_engine.sh
if [ -z "${CONTAINER_EXE}" ]; then
    osascript -e 'display dialog "Podman or Docker container engine is not running. Please ensure either Podman or Docker is installed and running" with title "Sastre-Pro" buttons {"OK"} default button "OK" with icon POSIX file "/tmp/sastre-pro/caution.png"'
    exit 1
fi
echo "=============Sastre-Pro post installation process started============="

#remove sastre-pro containers and images
list_existing_sastre_images=$($CONTAINER_EXE images --filter=reference="localhost/sastre-pro:latest" -q)
# Sleep interval in seconds
SLEEP_INTERVAL=0

function are_containers_stopped() {
    local containers
    containers=$($CONTAINER_EXE ps -q --filter "ancestor=localhost/sastre-pro:latest")
    [[ -z "$containers" ]]
}

# Function to check if the list of containers is empty
function are_containers_removed() {
    local containers
    containers=$($CONTAINER_EXE ps -aq --filter "ancestor=localhost/sastre-pro:latest")
    [[ -z "$containers" ]]
}

if [ -z "$list_existing_sastre_images" ]; then
    echo "[4/4] [DONE] No sastre-pro:latest image(s) found."
else
    echo "sastre-pro:latest image(s) found, going to delete sastre-pro containers if any"
    $CONTAINER_EXE stop $($CONTAINER_EXE ps -q --filter "ancestor=localhost/sastre-pro:latest")
    while ! are_containers_stopped; do
      echo "Waiting for containers to stop..."
      sleep "$SLEEP_INTERVAL"
    done
    $CONTAINER_EXE rm $($CONTAINER_EXE ps -aq --filter "ancestor=localhost/sastre-pro:latest")
    
    while ! are_containers_removed; do
      echo "Waiting for containers to be removed..."
      sleep "$SLEEP_INTERVAL"
    done

    for image_id in $list_existing_sastre_images; do
        echo "Deleting sastre-pro image: $image_id"
        $CONTAINER_EXE rmi -f "$image_id"
    done
    echo "[4/4] [DONE] Successfully deleted latest sastre-pro image"
fi

if [ -e "/tmp/sastre-pro/sastre-pro.tar.gz" ]; then
    gunzip /tmp/sastre-pro/sastre-pro.tar.gz
else
    echo "File /tmp/sastre-pro/sastre-pro.tar.gz does not exist."
fi

$CONTAINER_EXE load -i /tmp/sastre-pro/sastre-pro.tar

if [ $? -eq 0 ]; then
    echo "Latest sastre-pro image loaded successfully"
else
    echo "Failed to load latest sastre-pro image with exit code $?"
fi

rm /tmp/sastre-pro/sastre-pro.tar
if [ ! -d ~/sastre-pro ]; then
    mkdir ~/sastre-pro    
fi

# Check if the sastre-volume already exists
if [ ! -d ~/sastre-pro/sastre-volume ]; then
    mkdir ~/sastre-pro/sastre-volume 
    chmod go+w ~/sastre-pro/sastre-volume
    echo "sastre-volume created successfully"
else
    echo "sastre-volume folder already exists"
fi

cp -r /tmp/sastre-pro/container_engine.sh /tmp/sastre-pro/sastre.icns /tmp/sastre-pro/sastre-pro.sh /tmp/sastre-pro/uninstall.sh /tmp/sastre-pro/uninstall.app ~/sastre-pro/
rm -r /tmp/sastre-pro

echo "=============Sastre-Pro post installation process finished============="
CONTAINER_NAME=$(basename "$CONTAINER_EXE")
dialog_message="The Sastre-Pro image has been successfully loaded into the $CONTAINER_NAME container engine."
osascript -e "display dialog \"$dialog_message\" with title \"Sastre-Pro\" buttons {\"OK\"} default button \"OK\" with icon POSIX file \"$HOME/sastre-pro/sastre.icns\""